version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:17.0.6
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Deploy
          command: mvn deploy -s .circleci/settings.xml

workflows:
  sample:
    jobs:
      - build-and-deploy
