version: 2.1

jobs:
  build-and-release:
    docker:
      - image: cimg/openjdk:17.0.6
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Release
          command: mvn --batch-mode release:prepare release:perform -s .circleci/settings.xml

workflows:
  sample:
    jobs:
      - build-and-release
